version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: pimpmypack
    env:
        - CGO_ENABLED=0
    goos:
        - linux
        - darwin

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

docker_manifests:
  - name_template: "ghcr.io/angak0k/pimpmypack:{{ .Tag }}"
    image_templates:
      - "ghcr.io/angak0k/pimpmypack:{{ .Tag }}-amd64"
  - name_template: "ghcr.io/angak0k/pimpmypack:latest"
    image_templates:
      - "ghcr.io/angak0k/pimpmypack:latest-amd64"

dockers:
  - image_templates:
      - "ghcr.io/angak0k/pimpmypack:{{ .Tag }}-amd64"
      - "ghcr.io/angak0k/pimpmypack:latest-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    ids:
      - pimpmypack
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"

changelog:
  sort: asc
  filters:
    exclude:
      - "^test:"
