// Package api_doc Code generated by swaggo/swag. DO NOT EDIT
package api_doc

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/refresh": {
            "post": {
                "description": "Exchange a valid refresh token for a new access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Refresh access token",
                "parameters": [
                    {
                        "description": "Refresh Token",
                        "name": "refresh_token",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/security.RefreshTokenInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/security.RefreshResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid or expired refresh token",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/confirmemail": {
            "get": {
                "description": "Confirm email address by providing username and email",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Public"
                ],
                "summary": "Confirm email address",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apitypes.OkResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/forgotpassword": {
            "post": {
                "description": "Send a new password to the user's email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Public"
                ],
                "summary": "Reset password",
                "parameters": [
                    {
                        "description": "Email Address",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/accounts.ForgotPasswordInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apitypes.OkResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Log in a user by providing username and password\nReturns access token (short-lived) and refresh token (long-lived)\nUse remember_me to extend refresh token lifetime",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Public"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Credentials Info",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/accounts.LoginInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful with access and refresh tokens",
                        "schema": {
                            "$ref": "#/definitions/security.TokenPairResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials or account not confirmed",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Register a new user with username, password, email, firstname, and lastname",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Public"
                ],
                "summary": "Register new user",
                "parameters": [
                    {
                        "description": "Register Informations",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/accounts.RegisterInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apitypes.OkResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sharedlist/{sharing_code}": {
            "get": {
                "description": "Retrieves pack metadata and contents using a sharing code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Public"
                ],
                "summary": "Get shared pack with metadata",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pack sharing code",
                        "name": "sharing_code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Shared pack with metadata and contents",
                        "schema": {
                            "$ref": "#/definitions/packs.SharedPackResponse"
                        }
                    },
                    "404": {
                        "description": "Pack not found or not shared",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/importfromlighterpack": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Import from lighterpack csv pack file",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Packs"
                ],
                "summary": "Import from lighterpack csv pack file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "CSV file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "CSV data imported successfully with pack ID",
                        "schema": {
                            "$ref": "#/definitions/packs.ImportLighterPackResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid CSV format",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/myaccount": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get information of the currently logged-in user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accounts"
                ],
                "summary": "Get account info",
                "responses": {
                    "200": {
                        "description": "Account Information",
                        "schema": {
                            "$ref": "#/definitions/accounts.Account"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Account not found",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Update information of the currently logged-in user (email, name, preferences only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accounts"
                ],
                "summary": "Update account info",
                "parameters": [
                    {
                        "description": "Account update data (excludes role, status, username)",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/accounts.AccountUpdateInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/accounts.Account"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/myinventory": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Retrieves a list of all inventories of the user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Inventories"
                ],
                "summary": "Get all inventories of the user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/inventories.Inventory"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No Inventory Found",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Creates an inventory",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Inventories"
                ],
                "summary": "Create an inventory",
                "parameters": [
                    {
                        "description": "Inventory",
                        "name": "inventory",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventories.InventoryCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Inventory Updated",
                        "schema": {
                            "$ref": "#/definitions/inventories.Inventory"
                        }
                    },
                    "400": {
                        "description": "Invalid payload",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/myinventory/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Retrieves an inventory by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Inventories"
                ],
                "summary": "Get an inventory by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Inventory ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Inventory",
                        "schema": {
                            "$ref": "#/definitions/inventories.Inventory"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "This item does not belong to you",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Inventory not found",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Updates an inventory by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Inventories"
                ],
                "summary": "Update an inventory by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Inventory ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Inventory",
                        "name": "inventory",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/inventories.InventoryUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Inventory Updated",
                        "schema": {
                            "$ref": "#/definitions/inventories.Inventory"
                        }
                    },
                    "400": {
                        "description": "Invalid payload",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "This item does not belong to you",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Deletes an inventory by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Inventories"
                ],
                "summary": "Delete an inventory by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Inventory ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Inventory deleted",
                        "schema": {
                            "$ref": "#/definitions/apitypes.OkResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID format",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "This item does not belong to you",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/mypack": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Create a new pack",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Packs"
                ],
                "summary": "Create a new pack",
                "parameters": [
                    {
                        "description": "Pack",
                        "name": "pack",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/packs.PackCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Pack created",
                        "schema": {
                            "$ref": "#/definitions/packs.Pack"
                        }
                    },
                    "400": {
                        "description": "Invalid Body format",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/mypack/:id/packcontent": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Create a new pack content",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Packs"
                ],
                "summary": "Create a new pack content",
                "parameters": [
                    {
                        "description": "Pack Content",
                        "name": "packcontent",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/packs.PackContent"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/packs.PackContent"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/mypack/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get pack by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Packs"
                ],
                "summary": "Get My pack by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pack ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/packs.Pack"
                        }
                    },
                    "400": {
                        "description": "Invalid ID format",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "This pack does not belong to you",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Pack not found",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Update a pack by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Packs"
                ],
                "summary": "Update a pack by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pack ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Pack",
                        "name": "pack",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/packs.PackUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Pack updated",
                        "schema": {
                            "$ref": "#/definitions/packs.Pack"
                        }
                    },
                    "400": {
                        "description": "Invalid Payload",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "This pack does not belong to you",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Delete a pack by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Packs"
                ],
                "summary": "Delete a pack by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pack ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Pack deleted",
                        "schema": {
                            "$ref": "#/definitions/apitypes.OkResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID format",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "This pack does not belong to you",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/mypack/{id}/image": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Upload or update an image for a pack. Only the pack owner can upload images.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pack Images"
                ],
                "summary": "Upload or update pack image",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pack ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Image file (JPEG, PNG, or WebP, max 5MB)",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Image uploaded successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request or image",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Pack does not belong to user",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Pack not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "413": {
                        "description": "Payload too large",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Delete the image for a pack. Only the pack owner can delete images.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pack Images"
                ],
                "summary": "Delete pack image",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pack ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Image deleted successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid pack ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Pack does not belong to user",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Pack not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/mypack/{id}/packcontent/{item_id}": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Update My pack content ID by Pack ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Packs"
                ],
                "summary": "Update My pack content ID by Pack ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pack ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Item ID",
                        "name": "item_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Pack Content",
                        "name": "packcontent",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/packs.PackContentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Pack Content updated",
                        "schema": {
                            "$ref": "#/definitions/packs.PackContent"
                        }
                    },
                    "400": {
                        "description": "Invalid Body format",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "This pack does not belong to you",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Delete a pack content by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Packs"
                ],
                "summary": "Delete a pack content by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pack ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Item ID",
                        "name": "item_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Pack Item deleted",
                        "schema": {
                            "$ref": "#/definitions/apitypes.OkResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID format",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "This pack does not belong to you",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/mypack/{id}/packcontents": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get pack content by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Packs"
                ],
                "summary": "Get pack content by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pack Content ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Pack Item",
                        "schema": {
                            "$ref": "#/definitions/packs.PackContent"
                        }
                    },
                    "400": {
                        "description": "Invalid ID format",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "This pack does not belong to you",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Pack not found",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/mypack/{id}/share": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Generate a sharing code for a pack to make it publicly accessible (idempotent)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Packs"
                ],
                "summary": "Share a pack by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pack ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Pack shared successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid ID format",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "This pack does not belong to you",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Pack not found",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Remove the sharing code from a pack to make it private (idempotent)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Packs"
                ],
                "summary": "Unshare a pack by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pack ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Pack unshared successfully",
                        "schema": {
                            "$ref": "#/definitions/apitypes.OkResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID format",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "This pack does not belong to you",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Pack not found",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/mypacks": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Get my packs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Packs"
                ],
                "summary": "Get My Packs",
                "responses": {
                    "200": {
                        "description": "Packs",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/packs.Pack"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No pack found",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/mypassword": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Update the password of the current logged-in user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accounts"
                ],
                "summary": "Update password",
                "parameters": [
                    {
                        "description": "Current and New Password",
                        "name": "password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/accounts.PasswordUpdateInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Password updated",
                        "schema": {
                            "$ref": "#/definitions/apitypes.OkResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apitypes.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/packs/{id}/image": {
            "get": {
                "description": "Get the image for a pack. Public packs are accessible without authentication.",
                "produces": [
                    "image/jpeg"
                ],
                "tags": [
                    "Pack Images"
                ],
                "summary": "Get pack image",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pack ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Invalid pack ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized (for private packs)",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden (for private packs not owned by user)",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Pack not found or has no image",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "accounts.Account": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastname": {
                    "type": "string"
                },
                "preferred_currency": {
                    "type": "string"
                },
                "preferred_unit_system": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "accounts.AccountUpdateInput": {
            "type": "object",
            "required": [
                "email",
                "firstname",
                "lastname"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                },
                "preferred_currency": {
                    "type": "string"
                },
                "preferred_unit_system": {
                    "type": "string"
                }
            }
        },
        "accounts.ForgotPasswordInput": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "accounts.LoginInput": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "remember_me": {
                    "description": "optional, defaults to false",
                    "type": "boolean"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "accounts.PasswordUpdateInput": {
            "type": "object",
            "required": [
                "current_password",
                "new_password"
            ],
            "properties": {
                "current_password": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string"
                }
            }
        },
        "accounts.RegisterInput": {
            "type": "object",
            "required": [
                "email",
                "firstname",
                "lastname",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "apitypes.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "apitypes.OkResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "inventories.Inventory": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "item_name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "weight": {
                    "type": "integer"
                }
            }
        },
        "inventories.InventoryCreateRequest": {
            "type": "object",
            "required": [
                "category",
                "item_name"
            ],
            "properties": {
                "category": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "item_name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                },
                "weight": {
                    "type": "integer"
                }
            }
        },
        "inventories.InventoryUpdateRequest": {
            "type": "object",
            "required": [
                "category",
                "item_name"
            ],
            "properties": {
                "category": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "item_name": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                },
                "weight": {
                    "type": "integer"
                }
            }
        },
        "packs.ImportLighterPackResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "pack_id": {
                    "type": "integer"
                }
            }
        },
        "packs.Pack": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "has_image": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "pack_description": {
                    "type": "string"
                },
                "pack_items_count": {
                    "type": "integer"
                },
                "pack_name": {
                    "type": "string"
                },
                "pack_weight": {
                    "type": "integer"
                },
                "sharing_code": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "packs.PackContent": {
            "type": "object",
            "properties": {
                "consumable": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "item_id": {
                    "type": "integer"
                },
                "pack_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "worn": {
                    "type": "boolean"
                }
            }
        },
        "packs.PackContentRequest": {
            "type": "object",
            "properties": {
                "consumable": {
                    "type": "boolean"
                },
                "inventory_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "worn": {
                    "type": "boolean"
                }
            }
        },
        "packs.PackContentWithItem": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "consumable": {
                    "type": "boolean"
                },
                "currency": {
                    "type": "string"
                },
                "inventory_id": {
                    "type": "integer"
                },
                "item_description": {
                    "type": "string"
                },
                "item_name": {
                    "type": "string"
                },
                "item_url": {
                    "type": "string"
                },
                "pack_content_id": {
                    "type": "integer"
                },
                "pack_id": {
                    "type": "integer"
                },
                "price": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "weight": {
                    "type": "integer"
                },
                "worn": {
                    "type": "boolean"
                }
            }
        },
        "packs.PackCreateRequest": {
            "type": "object",
            "required": [
                "pack_name"
            ],
            "properties": {
                "pack_description": {
                    "type": "string"
                },
                "pack_name": {
                    "type": "string"
                }
            }
        },
        "packs.PackUpdateRequest": {
            "type": "object",
            "required": [
                "pack_name"
            ],
            "properties": {
                "pack_description": {
                    "type": "string"
                },
                "pack_name": {
                    "type": "string"
                }
            }
        },
        "packs.SharedPackInfo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "has_image": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "pack_description": {
                    "type": "string"
                },
                "pack_name": {
                    "type": "string"
                }
            }
        },
        "packs.SharedPackResponse": {
            "type": "object",
            "properties": {
                "contents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/packs.PackContentWithItem"
                    }
                },
                "pack": {
                    "$ref": "#/definitions/packs.SharedPackInfo"
                }
            }
        },
        "security.RefreshResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                }
            }
        },
        "security.RefreshTokenInput": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "security.TokenPairResponse": {
            "type": "object",
            "properties": {
                "access_expires_in": {
                    "type": "integer"
                },
                "access_token": {
                    "type": "string"
                },
                "refresh_expires_in": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                },
                "token": {
                    "description": "Backward compatibility - same as AccessToken",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "pmp-dev.alki.earth",
	BasePath:         "/api",
	Schemes:          []string{"https"},
	Title:            "PimpMyPack API",
	Description:      "API server to manage Backpack Inventory and Packing Lists",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
